version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "devplanet-demo-serverless-rest-api"
s3_prefix = "devplanet-demo-serverless-rest-api"
region = "ap-southeast-2"
confirm_changeset = true
parameter_overrides = "DeployEnv=\"dev\""
capabilities = "CAPABILITY_IAM"
image_repositories = []
resolve_s3 = true
